### ISSUE TITLE
Error when loading the library

### ISSUE THREAD

**Issue by Antonin-Deniau** [ProcessOut/processout-node#4]
I've got an error when i try to load the library like this:

```javascript
'use strict';
var _ = require('lodash');
var util = require('util');

var ProcessOut = require('processout');

function request_invoice(req, res) {
  res.json("plop");
}

module.exports = {
  request_invoice: request_invoice,
};
```
It's throw the error:
```
Error initializing middleware
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/invoice_api/node_modules/processout/index.js:5:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I've got the same error with node v4.2.2 & v5.10.1

**Comment by manuel-huez** [comment]
The npm library has not yet been fully tested -- it is automatically generated following our API specifications.
The syntax error should now be fixed in the `3.1.0-0` version. Can you confirm?

**Comment by Antonin-Deniau** [comment]
That's work, thanks!

**Comment by manuel-huez** [comment]
Awesome! Please don't hesitate to submit another issue if you find any other problem
